package-lock.json
package.json
src/components/Login/Login.tsx
src/styles/style.css

Arreglo del Login, Login Listo

Login listo

---

src/app/in/security/page.tsx
src/app/page.tsx
src/components/Security2Fa/Security2Fa.tsx
src/components/buttonSecurity/ButtonSecurity.tsx

Creacion de seguridad con generacion de Qr y contraseña Secret

creacion de seguridad FA

---

src/app/in/maitenance/page.tsx
src/components/adminUsersActions/BlockUser.tsx
src/components/adminUsersActions/DeleteUser.tsx
src/components/dashboard/ItemsSideBarTop.tsx
src/components/dashboard/ItemsSidebarBot.tsx
src/components/dashboard/Logout.tsx
src/components/dashboard/Sidebar.tsx
src/helpers/pathRoutes.ts

* Vista maintenance
* No condicionado para admin

Feature bpv 37 fhdzleon

---

package-lock.json
src/app/in/list/page.tsx
src/components/Login/Login.tsx
src/components/Security2Fa/Security2Fa.tsx
src/components/detailUserList/DetailUserList.tsx

cambios en el login y en la lista de usuarios(arreglos)

cambios en el login y la lista de usuarios

---

src/styles/style.css

Cambios en el estilo Responsive

Feature login4 vane

---

src/app/in/list/[id]/page.tsx
src/app/in/list/page.tsx
src/components/detailUserList/DetailUserList.tsx

cambios en el detalle de usuario y la tabla

---

src/app/in/maitenance/page.tsx
src/components/FormComponent/Button.tsx
src/components/adminUsersActions/BlockUser.tsx
src/components/adminUsersActions/DeleteUser.tsx
src/components/adminUsersActions/EditUser.tsx
src/components/deliverableWidget/DeliverableWidget.tsx
src/components/invoiceWidget/InvoiceWidget.tsx

* Agrego Hover a los botones de la vista UserDetail
* Unificación de tablas Capitalización de Titulo
* Imagen en la vista Maintenance

Hover Botones userDetail, Img mantineance, unitables

---

src/components/Login/Login.tsx
src/middleware.ts

midlleware on

---

src/components/CreateUserForm/UpdateUser.tsx

* Renderizado del formulario de edición condicionado para mi cuenta y cuenta de otro usuario

Renderizado condicionado de edicion de cuenta

---

src/components/adminUsersActions/BlockUser.tsx
src/components/adminUsersActions/DeleteUser.tsx
src/components/dashboard/Avatar.tsx
src/styles/style.css

Cambio del boton succes de sweet alert

Cambio el boton morado del sweet alert por el azul institucional

---

src/app/globals.css
src/app/in/deliverables/Deliverables.tsx
src/app/in/deliverables/page.ts
src/components/dashboard/ItemsSideBarTop.tsx
src/components/deliverablesActions/DeleteDeliverable.tsx
src/components/deliverablesActions/DownloadDeliverable.tsx
src/components/deliverablesActions/EditDeliverable.tsx
src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesActions/ViewDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/components/deliverablesView/Searchbar.tsx
src/helpers/deliverableData.ts
src/helpers/pathRoutes.ts
tailwind.config.ts

- Maquetado vista deliverables
- Componentes actionsDeliverables modularizadas
- Componente upload maquetado 
- Modal upload 
- Agregada ruta PATHROUTES.DELIVERABLES

maqueta vista deliverables actions modularizadas upload

---

src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/components/deliverablesView/Searchbar.tsx
src/helpers/deliverableData.ts

deliverable list paginated

---

src/app/in/list/page.tsx
src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/context/AuthContext.tsx
src/helpers/deliverableData.ts

* Agregados estados globales allUsers y deliverablesData

Estados globales deliverables y allUsers

---

src/app/page.tsx
src/components/deliverablesActions/DeleteDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/context/AuthContext.tsx

deliverable back integrated

---

src/components/deliverablesActions/DownloadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/interfaces/downLoadProps.ts

Feature bpv 25 fhdzleon

---

src/helpers/auth.helper.tsx

getUserData fix

---

src/app/in/list-invoices/[id]/page.tsx
src/app/in/list-invoices/page.tsx
src/components/DetailInvoice/DetailInvoice.tsx

Cambios en el estilo, agregue un modal por ahora hasta tener la vista previa, y agregue el back (todo esto en la parte de facturas)

cambios en la factura

---

src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx

* permisos para admin habilitados
* Upload avanzado, ya sube files

permisos para dmin habilitados

---

src/app/globals.css
src/app/in/deliverables/Deliverables.tsx
src/app/in/layout.tsx
src/app/in/list-invoices/page.tsx
src/app/in/list/page.tsx
src/app/layout.tsx
src/app/page.tsx
src/components/dashboard/Avatar.tsx
src/components/deliverableWidget/DeliverableWidget.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/context/AuthContext.tsx
src/helpers/auth.helper.tsx

mejorand ux con loader

---

src/components/deliverablesActions/DeleteDeliverable.tsx
src/components/deliverablesActions/DownloadDeliverable.tsx
src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/context/AuthContext.tsx
src/helpers/fetchDeliverables.ts

* Upload y delete file fix useEffect

Feature bpv 28 fhdzleon

---

src/app/in/list-invoices/page.tsx

Cambios en la renderizacion de facturas

cambios en facturas

---

src/app/in/create-user/Create-user1.tsx
src/app/in/list-invoices/page.tsx
src/app/in/my-account/My-Account.tsx
src/components/CreateUserForm/UpdateUser.tsx

Este fue quien nos tumbo el front falto el use Client

fixing edit user use client

---

src/components/InvoicesButton/Buttondowland.tsx
src/components/List-Invoice/List-Invoice.tsx
src/components/deliverablesView/Searchbar.tsx
src/components/deliverablesView/permissionpanel.tsx
src/context/AuthContext.tsx

Creacion del Componente de busqueda por nombre y arreglo de permisos

creacion del search y arreglo del panel

---

src/components/deliverablesActions/DownloadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/interfaces/downLoadProps.ts

Feature bpv 24 fhdzleon

---

src/app/in/company/AddCompanyPage.tsx
src/app/in/company/page.ts
src/components/company/AddCompanyComponent.tsx

Feature bpv 6 gio2

---

src/components/deliverableWidget/DeliverableWidget.tsx
src/components/deliverablesActions/DownloadDeliverable.tsx
src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/components/sortDeliverables/SortDeliverable.tsx
src/context/AuthContext.tsx
src/interfaces/downLoadProps.ts

* Sort deliverables done
* Sweet alerts in all comps

Sort deliverables, sweetalerts

---

src/components/InvoicesButton/Buttondowland.tsx
src/components/List-Invoice/List-Invoice.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/components/deliverablesView/Searchbar.tsx

prueba del  buscador

---

src/app/in/company/list/page.tsx

company list

---

src/components/deliverablesActions/UploadForType.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/helpers/fetchDeliverables.ts
src/helpers/getDeliverableExtension.ts

* Cambios en la forma de subir archivos 
* Verificacion de nombre existente desde front
* Verificacion de icono desde front ya no desde back (cambio el upload file)

upload deliverable change, verification done

---

src/app/forgotPassword/page.tsx
src/app/in/company/[id]/edit/page.tsx
src/app/in/company/[id]/page.tsx
src/app/in/company/list/page.tsx
src/components/Buttons/BackButton.tsx

changes company

---

src/app/in/company/list/page.tsx
src/components/List-Invoice/ListInvoiceComponent.tsx
src/components/Search/Search.tsx

Incorporacion de Buscadores por nombre y paginacion en facturacion y empresas

incorporacion de paginacion y buscador por nombre

---

src/app/in/company/[id]/page.tsx
src/app/in/company/list/page.tsx
src/app/in/invoices/list/page.tsx

Feature bpv 211 gio

---

src/components/List-Invoice/ListInvoiceComponent.tsx
src/components/List-Invoice/PanelPermissionInvoices.tsx

incorporacion de permisos a Facturacion

incorporacion a Fcaturacion

---

src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/context/AuthContext.tsx
src/helpers/fetchDeliverables.ts
src/helpers/getDeliverableExtension.ts

* upload folders and links whit parentsId

upload folders and links

---

src/components/deliverablesActions/LinkDeliverable.tsx
src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/components/deliverablesView/Searchbar.tsx
src/interfaces/LinkDeliverablesProps.ts

* Link deliverables done
* view links
* Span searchbar

link deliverables

---

src/components/deliverablesActions/EditDeliverable.tsx
src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/interfaces/editDeliverablesProps.ts
test.ts

* Edit files 
* Edit Links
* Google add file button hidden

edit deliverables

---

src/app/in/company/list/page.tsx
src/app/in/users/list/page.tsx
tailwind.config.ts

icon change

---

_doc/metodos.http
src/app/in/company/list/page.tsx
src/app/in/invoices/me/page.tsx
src/app/in/layout.tsx
src/components/ButtonAlerts/ButtonAlerts.tsx
src/components/List-Invoice/ListInvoiceComponent.tsx
src/components/List-Invoice/PanelPermissionInvoices.tsx
src/components/Users/UsersListComponent.tsx
src/helpers/auth.helper.tsx
src/interfaces/InvoiceInterface.ts

Arreglo de paginacion de empresas

Feature search vane

---

src/app/forgotPassword/page.tsx
src/app/in/company/[id]/edit/page.tsx
src/app/in/company/[id]/invoices/page.tsx
src/app/in/company/[id]/users/page.tsx
src/app/in/company/list/page.tsx
src/components/dashboard/ItemsAdminUser.tsx

back button

---

src/app/in/invoices/me/page.tsx
src/components/List-Invoice/ListInvoiceComponent.tsx

integracion de permisos en facturacion lista y que desde los usuarios solo se vean las acciones no los permisos

integracion de permisos en facturacion lista

---

src/app/in/page.tsx
src/components/deliverableWidget/DeliverableWidget.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/components/invoiceWidget/InvoiceWidget.tsx
src/components/notificationsWidget/NotificationCard.tsx
src/components/notificationsWidget/Notifications.tsx
src/helpers/UsersData.tsx

Feature bpv 208 fhdzleon

---

src/app/in/invoices/[id]/edit/page.tsx
src/components/dashboard/Avatar.tsx
src/components/dashboard/Sidebar.tsx
src/components/invoice/UpdateInvoiceComponent.tsx
src/context/AuthContext.tsx

Frank front

---

src/app/in/company/[id]/details/page.tsx
src/app/in/company/[id]/edit/page.tsx
src/app/in/company/[id]/invoices/page.tsx
src/app/in/company/[id]/users/page.tsx
src/app/in/company/create/AddCompanyPage.tsx
src/app/in/company/list/page.tsx
src/app/in/invoices/[id]/edit/page.tsx
src/app/in/invoices/create/page.tsx
src/app/in/invoices/list/page.tsx
src/components/Buttons/BackButton.tsx
src/components/Users/DetailUserList.tsx

front style change

---

src/components/InvoicesButton/ButtonDelete.tsx
src/components/InvoicesButton/Buttondowland.tsx
src/components/List-Invoice/ListInvoiceComponent.tsx
src/components/Users/UsersListComponent.tsx
src/components/icons/EditIcon.tsx
src/components/icons/EyeIcon.tsx
src/components/icons/UploadIcon.tsx
src/components/invoice/VoucherUpload.tsx

icon change over view

---

src/app/forgotPassword/[emailEncrypt]/page.tsx
src/app/forgotPassword/page.tsx

forgot password

---

src/app/forgotPassword/[emailEncrypt]/page.tsx
src/app/forgotPassword/page.tsx

forgot password new change

---

src/components/List-Invoice/ListInvoiceComponent.tsx
src/components/Users/UsersListComponent.tsx

gio change

---

src/app/in/invoices/me/page.tsx
src/components/ButtonAlerts/ButtonAlerts.tsx
src/components/List-Invoice/ListInvoiceComponent.tsx
src/components/List-Invoice/PanelPermissionInvoices.tsx
src/components/deliverablesView/permissionpanel.tsx

Cambie el panel para que siempre se vea en la misma posición, y tambien elimine el editar de permisos en invoices

Feature notifications2 vane

---

src/components/InvoicesButton/Buttondowland.tsx
src/components/Search/Search.tsx
src/components/deliverablesActions/DownloadDeliverable.tsx
src/components/deliverablesActions/UploadDeliverable.tsx
src/components/deliverablesView/DeliverablesList.tsx
src/components/deliverablesView/Searchbar.tsx
src/components/filterDeliverableForBussines/FilterDeliverableForBussines.tsx
src/interfaces/downLoadProps.ts
test.ts

* Large File Alert
* Deliverable Name Input Validation
* Download Deliverable from Backend
* Searchbar and Select Button Color

feddback lucas, download from backend

---

src/components/deliverablesActions/UploadDeliverable.tsx
src/components/notificationsWidget/NotificationCard.tsx
src/components/notificationsWidget/Notifications.tsx
src/helpers/UsersData.tsx

notifications-widget v2

---

src/components/notificationsWidget/NotificationCard.tsx
src/components/notificationsWidget/Notifications.tsx
src/context/WebSocket.tsx
src/helpers/UsersData.tsx
src/interfaces/notifications.ts

Update bpv 252 fhdzleon

---

src/components/invoice/UpdateInvoiceComponent.tsx

Frank front 2

---

src/helpers/UsersData.tsx

Fix bvp 252

---

src/app/in/company/[id]/edit/page.tsx
src/components/List-Invoice/ListInvoiceComponent.tsx
src/components/Users/UpdateUser.tsx
src/components/company/AddCompanyComponent.tsx
src/components/invoice/VoucherUpload-backup.tsx
src/components/notificationsWidget/NotificationCard.tsx

Frank front 3

---

src/components/notificationsWidget/Notifications.tsx

bearer added notifications widget

token notifications

---

src/app/in/company/list/page.tsx
src/app/in/invoices/list/page.tsx
src/components/Buttons/ButtonAdd.tsx
src/components/Buttons/ButtonSendEmail.tsx
src/components/Users/CreateUserForm.tsx
src/components/company/AddCompanyComponent.tsx

Frank front 4

---

src/components/Buttons/ButtonSendEmail.tsx

update email send message

---

src/app/in/users/create/Create-user1.tsx

boton maldito

---

src/app/in/company/list/page.tsx
src/app/in/invoices/list/page.tsx
src/components/Search/Search.tsx
src/components/Users/UsersListComponent.tsx

cambios en el modelo responsive

Feature notif vane2

---

src/components/adminUsersActions/BlockUser.tsx
src/components/deliverablesActions/UploadDeliverable.tsx

* Arreglos en el modal de deliverables

Update details fhdzleon
